name: WinCI2024b

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/FilipCZ/test2x/main/loop.ps1 -OutFile loop.ps1
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile serv.zip
    - name: Extract
      run: Expand-Archive serv.zip
    - name: Auth
      run: |
        Rename-Item -Path ".\serv\ngrok.exe" -NewName ".\serv\clicon.exe"
        .\serv\clicon.exe config add-authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
        Set-LocalUser -Name "installer" -Password (ConvertTo-SecureString -AsPlainText "aaa.123" -Force)
    - name: Create Tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\serv\clicon.exe tcp --region=eu 3389"'
    - name: Keep-alive loop (1/13)
      run: |
        ./loop.ps1
        Stop-Process -Name "ngrok"
        Stop-Process -Name "clicon"
        Start-Sleep -Seconds 900
    - name: Keep-alive loop (2/13)
      run: |
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\serv\clicon.exe tcp --region=eu 3389"'
        ./loop.ps1
        Stop-Process -Name "ngrok"
        Stop-Process -Name "clicon"
        Start-Sleep -Seconds 900
    - name: Keep-alive loop (3/13)
      run: |
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\serv\clicon.exe tcp --region=eu 3389"'
        ./loop.ps1
        Stop-Process -Name "ngrok"
        Stop-Process -Name "clicon"
        Start-Sleep -Seconds 900
    - name: Keep-alive loop (4/13)
      run: |
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\serv\clicon.exe tcp --region=eu 3389"'
        ./loop.ps1
        Stop-Process -Name "ngrok"
        Stop-Process -Name "clicon"
        Start-Sleep -Seconds 900
    - name: Keep-alive loop (5/13)
      run: |
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\serv\clicon.exe tcp --region=eu 3389"'
        ./loop.ps1
        Stop-Process -Name "ngrok"
        Stop-Process -Name "clicon"
        Start-Sleep -Seconds 900
    - name: Keep-alive loop (6/13)
      run: |
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\serv\clicon.exe tcp --region=eu 3389"'
        ./loop.ps1
        Stop-Process -Name "ngrok"
        Stop-Process -Name "clicon"
        Start-Sleep -Seconds 900
    - name: Keep-alive loop (7/13)
      run: |
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\serv\clicon.exe tcp --region=eu 3389"'
        ./loop.ps1
        Stop-Process -Name "ngrok"
        Stop-Process -Name "clicon"
        Start-Sleep -Seconds 900
    - name: Keep-alive loop (8/13)
      run: |
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\serv\clicon.exe tcp --region=eu 3389"'
        ./loop.ps1
        Stop-Process -Name "ngrok"
        Stop-Process -Name "clicon"
        Start-Sleep -Seconds 900
    - name: Keep-alive loop (9/13)
      run: |
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\serv\clicon.exe tcp --region=eu 3389"'
        ./loop.ps1
        Stop-Process -Name "ngrok"
        Stop-Process -Name "clicon"
        Start-Sleep -Seconds 900
    - name: Keep-alive loop (10/13)
      run: |
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\serv\clicon.exe tcp --region=eu 3389"'
        ./loop.ps1
        Stop-Process -Name "ngrok"
        Stop-Process -Name "clicon"
        Start-Sleep -Seconds 900
    - name: Keep-alive loop (11/13)
      run: |
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\serv\clicon.exe tcp --region=eu 3389"'
        ./loop.ps1
        Stop-Process -Name "ngrok"
        Stop-Process -Name "clicon"
        Start-Sleep -Seconds 900
    - name: Keep-alive loop (12/13)
      run: |
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\serv\clicon.exe tcp --region=eu 3389"'
        ./loop.ps1
        Stop-Process -Name "ngrok"
        Stop-Process -Name "clicon"
        Start-Sleep -Seconds 900
    - name: Keep-alive loop (13/13)
      run: |
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\serv\clicon.exe tcp --region=eu 3389"'
        ./loop.ps1
        Stop-Process -Name "ngrok"
        Stop-Process -Name "clicon"
        Start-Sleep -Seconds 900
